// DEBUG VARIANT -- adds a read + printf of one intermediate tensor
// (kIntermediateTensorIndex / kIntermediateExpected from test_vector.h)
// so we can localize where int8 divergence first appears in the graph,
// rather than only seeing it at the final output. Original main.cpp is
// untouched -- fall back to it any time by rebuilding with that file
// instead of this one (update CMakeLists.txt's SRCS accordingly).

#include <cstdio>

#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "model_data.h"
#include "test_vector.h"

namespace {
// Arena size: your STM32 build needed ~16.4 KB of activations. TFLite Micro
// typically needs somewhat more overhead than ST's runtime for the same
// graph (its own interpreter bookkeeping, tensor metadata, etc). Starting
// generous since ESP32-C6 has plenty of RAM (512 KB) -- if AllocateTensors()
// fails, this is the first thing to increase; if it succeeds, check
// interpreter->arena_used_bytes() afterward and shrink this to match with
// some headroom, for an honest "actual RAM used" number in your thesis.
constexpr int kTensorArenaSize = 176 * 1024;
alignas(16) uint8_t tensor_arena[kTensorArenaSize];
}  // namespace

extern "C" void app_main(void) {
  printf("\n=== SmallTCN solar model on ESP32-C6 (TFLite Micro) ===\n\n");

  const tflite::Model* model = tflite::GetModel(g_model_data);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    printf("ERROR: Model schema version %lu != supported version %d\n",
           model->version(), TFLITE_SCHEMA_VERSION);
    return;
  }
  printf("Model loaded OK (schema version %lu)\n", model->version());

  // MicroMutableOpResolver (not AllOpsResolver, which was removed from
  // recent TFLite Micro versions) -- register exactly the ops this model
  // uses. Known from the STM32 analyze report's op table: Pad,
  // StridedSlice, Reshape, ExpandDims, Conv2D, Add, FullyConnected,
  // Gather. Relu/Quantize/Dequantize added defensively in case they
  // aren't fully fused into the surrounding ops on this runtime.
  static tflite::MicroMutableOpResolver<11> resolver;
  resolver.AddPad();
  resolver.AddStridedSlice();
  resolver.AddReshape();
  resolver.AddExpandDims();
  resolver.AddConv2D();
  resolver.AddAdd();
  resolver.AddFullyConnected();
  resolver.AddGather();
  resolver.AddRelu();
  resolver.AddQuantize();
  resolver.AddDequantize();

  static tflite::MicroInterpreter static_interpreter(
    model, resolver, tensor_arena, kTensorArenaSize,
    /*resource_variables=*/nullptr, /*profiler=*/nullptr,
    /*preserve_all_tensors=*/true);
  tflite::MicroInterpreter* interpreter = &static_interpreter;

  TfLiteStatus allocate_status = interpreter->AllocateTensors();
  if (allocate_status != kTfLiteOk) {
    printf("ERROR: AllocateTensors() failed. Try increasing kTensorArenaSize "
           "(currently %d bytes).\n", kTensorArenaSize);
    return;
  }
  printf("Tensors allocated. Arena used: %d / %d bytes\n",
         (int)interpreter->arena_used_bytes(), kTensorArenaSize);

  TfLiteTensor* input = interpreter->input(0);
  TfLiteTensor* output = interpreter->output(0);

  printf("Input:  dims=%d, bytes=%d, type=%d\n", input->dims->size,
         (int)input->bytes, input->type);
  printf("Output: dims=%d, bytes=%d, type=%d\n", output->dims->size,
         (int)output->bytes, output->type);

  // Load the REAL preprocessed+quantized test vector (from test_vector.h,
  // generated by prepare_esp32_deployment.py from an actual test-split
  // window -- not random data).
  if ((int)input->bytes != kTestInputContextLength * kTestInputChannels) {
    printf("ERROR: test vector size (%d) doesn't match model input size (%d)\n",
           kTestInputContextLength * kTestInputChannels, (int)input->bytes);
    return;
  }

  printf("\n--- DEBUG: kTestInput as embedded in firmware ---\n");
  for (int i = 0; i < input->bytes; i++) {
    printf("%d, ", (int)kTestInput[i]);
  }
  printf("\n");

  for (int i = 0; i < input->bytes; i++) {
    input->data.int8[i] = kTestInput[i];
  }

  printf("\n--- DEBUG: input tensor after copy (should be identical to above) ---\n");
  for (int i = 0; i < input->bytes; i++) {
    printf("%d, ", (int)input->data.int8[i]);
  }
  printf("\n");

  // Run inference multiple times and average -- a single sample can be
  // noisy (cache effects, etc); this matches the spirit of your STM32
  // "duration ... by sample" measurement over multiple runs.
  constexpr int kNumRuns = 20;
  int64_t total_us = 0;
  for (int run = 0; run < kNumRuns; run++) {
    int64_t start_us = esp_timer_get_time();
    TfLiteStatus invoke_status = interpreter->Invoke();
    int64_t end_us = esp_timer_get_time();
    if (invoke_status != kTfLiteOk) {
      printf("ERROR: Invoke() failed on run %d\n", run);
      return;
    }
    total_us += (end_us - start_us);
  }
  double avg_ms = (total_us / (double)kNumRuns) / 1000.0;

  printf("\n--- Timing ---\n");
  printf("Average inference time over %d runs: %.3f ms\n", kNumRuns, avg_ms);
  printf("Inferences/sec: %.2f\n", 1000.0 / avg_ms);

  // DEBUG: intermediate checkpoint using TfLiteEvalTensor
  printf("\n--- DEBUG: intermediate tensor check (idx=%d) ---\n", kIntermediateTensorIndex);
  TfLiteEvalTensor* mid_tensor = interpreter->GetTensor(kIntermediateTensorIndex);
  if (mid_tensor == nullptr) {
    printf("ERROR: interpreter->GetTensor(%d) returned null -- index out of range "
           "for this graph? Re-check the tensor list printed by "
           "prepare_esp32_deployment_debug.py.\n", kIntermediateTensorIndex);
  } else {
    int mid_actual_len = 1;
    for (int d = 0; d < mid_tensor->dims->size; d++) {
      mid_actual_len *= mid_tensor->dims->data[d];
    }

    if (mid_actual_len != kIntermediateLen) {
      printf("ERROR: intermediate tensor size on device (%d) != expected (%d) "
             "-- wrong tensor index, or shape mismatch vs. host reference.\n",
             mid_actual_len, kIntermediateLen);
    } else {
      int mid_max_abs_diff = 0;
      bool mid_all_match = true;
      for (int i = 0; i < kIntermediateLen; i++) {
        int actual = mid_tensor->data.int8[i];
        int expected = kIntermediateExpected[i];
        int diff = actual - expected;
        if (diff < 0) diff = -diff;
        if (diff > mid_max_abs_diff) mid_max_abs_diff = diff;
        if (actual != expected) mid_all_match = false;
      }
      printf("Intermediate max abs diff: %d (n=%d values)\n", mid_max_abs_diff, kIntermediateLen);
      printf("Intermediate exact match: %s\n", mid_all_match ? "YES" : "NO");
      
      // Print the first handful of values
      printf("First values -- actual: ");
      for (int i = 0; i < kIntermediateLen && i < 12; i++) printf("%d, ", (int)mid_tensor->data.int8[i]);
      printf("\nFirst values -- expected: ");
      for (int i = 0; i < kIntermediateLen && i < 12; i++) printf("%d, ", (int)kIntermediateExpected[i]);
      printf("\n");
    }
  }

  printf("\n--- Output check (last run) ---\n");
  bool all_match = true;
  int max_abs_diff = 0;
  for (int i = 0; i < kTestOutputLength; i++) {
    int actual = output->data.int8[i];
    int expected = kExpectedOutput[i];
    int diff = actual - expected;
    if (diff < 0) diff = -diff;
    if (diff > max_abs_diff) max_abs_diff = diff;
    if (actual != expected) all_match = false;
    printf("  [%2d] actual=%4d  expected=%4d  diff=%d\n", i, actual, expected, actual - expected);
  }
  printf("\nMax abs diff (int8 quantization units): %d\n", max_abs_diff);
  printf("Exact match: %s\n", all_match ? "YES" : "NO (small diffs are usually fine -- "
                                           "different int8 kernel implementations "
                                           "can round slightly differently; large "
                                           "diffs would indicate a real problem)");

  printf("\n=== Done ===\n");

  // Keep the task alive so output stays visible on the monitor.
  while (true) {
    vTaskDelay(pdMS_TO_TICKS(10000));
  }
}
